stages:
  - build
  - test

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  script:
    - echo "Building project..."

test:
  stage: test
  script:
    - echo "Testint project..."
