stages:
  - build
  - test

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  script:
    - echo "Building project..."

test:
  stage: test
  script:
    - echo "Testing project..."

secret_detection:
  stage: test
  script:
    - echo "Ejecutando Secret Detection..."
  artifacts:
    when: always
    reports:
      secret_detection: gl-secret-detection-report.json