stages:
  - build
  - test
  - deploy

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  image: node:20
  script:
    - echo "Building project..."
    - npm install
    - npm run build

test:
  stage: test
  script:
    - echo "Testing project..."

validate_secrets:
  stage: test
  needs: ["secret_detection"]
  image: alpine:latest
  script:
    - apk add --no-cache jq
    - echo "Validando reporte de Secret Detection..."
    - cat gl-secret-detection-report.json
    - SECRETS=$(jq '.vulnerabilities | length' gl-secret-detection-report.json)
    - echo "Se encontraron $SECRETS secretos"
    - |
      if [ "$SECRETS" -gt 0 ]; then
        echo "Se encontraron leaks: Deteniendo..."
        exit 1
      else
        echo "No se encontraron leaks"
      fi
  artifacts:
    when: always
    paths:
      - gl-secret-detection-report.json


push_to_github:
  stage: deploy
  script:
    - echo 'Todos los pipelines son correctos.'
  artifacts:
    when: on_success
  only:
    - main